dist: xenial

phpenv: 7.2

language: python

python:
  - "2.7"

jobs:
  include:
    - stage: deploy
      install:
        - pip install ansible
      script:
        - echo $ANSIBLE_VAULT_PASS > ansible/.vault_pass
        - cd ansible
        - make deploy env=production

    - stage: test
      script:
        - cd tests
        - composer install --no-interaction
        - cd ../ansible
        - make codecept env=production

addons:
  ssh_known_hosts:
  - 85.143.222.113
  apt:
    packages:
    - sshpass
