- name: Ensure {{deploy_user}} user is present
  user: name={{deploy_user}} state=present groups="sudo" password=$6$xwQLoX6jf9mnj$hma6y2JTpmrx7WXcILXCaU0iHtFT5hiPuo8y.13.RhOPfDUFDMxcO4PuTASJ9cbyujTN9edXZGYHbWd62BCLS/

- name: Ensure youll be able to deploy later on
  authorized_key: user={{deploy_user}} key="{{ lookup('file', 'files/id_rsa.pub') }}" state=present

- name: Ensure private key and public one are present
  copy: src="files/{{ item }}" dest="/home/deploy/.ssh/{{ item }}" mode=0600 owner=deploy
  with_items:
    - id_rsa.pub
#    - id_rsa

#- name: Add host
#  shell: ssh-keyscan {{ item }} >> /home/jenkins/.ssh/known_hosts
#  with_items:
#    - "{{known_hosts}}"
