---
# tasks file for lumen_deploy
- include: struct.yml
  become: true
  tags: setup

- include: dependency.yml
  become: true
  tags:
   - setup
   - dependency

- include: build.yml
  tags:
    - setup
    - deploy
    - build

- include: deploy.yml
  ansible_user: "{{ app_user }}"
  tags:
    - setup
    - deploy

- include: openapi.yml
  tags:
    - setup
    - deploy
    - openapi

- include: cron.yml
  tags:
    - setup
    - cron

- include: migrate.yml
  tags:
    - setup
    - migrate

- include: seed.yml
  tags:
    - setup
    - seed

- include: start.yml
  become: true
  tags: setup
