- hosts: server
  gather_facts: False

  pre_tasks:
    - include_vars:
        file: deploy-vars.yml
      when:
        - ansible_user is defined
        - ansible_user == 'deploy'
      tags:
        - deploy

  roles:
    - {role: gurkalov.lumen_deploy}
