- hosts: server
  gather_facts: False

  tasks:
    - name: Create docker folder
      file:
        path: /var/docker
        state: directory
        owner: "{{app_user}}"
        group: "{{app_group}}"
      tags:
        - setup

    - name: Copy docker
      copy:
        src: ../docker/{{item}}
        dest: /var/docker/docker/
      with_items:
        ['dump.sql','nginx/app.conf','nginx/nginx.conf']
      tags:
        - setup
        - deploy

    - name: Env
      copy:
        src: ../.env
        dest: /var/docker/.env
      tags:
        - setup
        - deploy

    - name: Docker-compose
      copy:
        src: ../docker-compose.production.yml
        dest: /var/docker/docker-compose.yml
      tags:
        - setup
        - deploy

    - name: Docker pull
      shell: docker pull gurkalov/eva
      args:
        chdir: /var/docker
      tags:
        - setup
        - deploy

    - name: Docker-compose restart
      shell: docker-compose down -v && docker-compose up -d
      args:
        chdir: /var/docker
      tags:
        - setup
        - deploy