- hosts: server
  user: root

  roles:
    - { role: gurkalov.deploy_user, tags: user }
    - { role: gurkalov.php_fpm, tags: php }
    - { role: geerlingguy.nginx, tags: nginx }
    - { role: geerlingguy.redis, tags: redis }
